import pandas as pd, glob

files = glob.glob('dataset_phase1/*_tick.csv')
df = pd.concat([pd.read_csv(f) for f in files[:5]])
print('=== TRAINING DATASET ===')
print(f'Rows: {len(df)}')
print(f'Speed mps: mean={df.speed_mps.mean():.2f} std={df.speed_mps.std():.4f} min={df.speed_mps.min():.2f} max={df.speed_mps.max():.2f}')
print(f'RSRP: {df.serving_rsrp_dbm.min():.1f} to {df.serving_rsrp_dbm.max():.1f}')
print(f'SINR: {df.serving_sinr_db.min():.1f} to {df.serving_sinr_db.max():.1f}')
print(f'HO: {df.ho_event.sum()} ({df.ho_event.mean()*100:.2f}%)')
print(f'RLF: {df.rlf_event.sum()} ({df.rlf_event.mean()*100:.2f}%)')
print(f'PP: {df.ping_pong.sum()} ({df.ping_pong.mean()*100:.2f}%)')
print(f'Margin dB: mean={df.best_margin_db.mean():.2f} std={df.best_margin_db.std():.2f}')

files2 = glob.glob('phase_3/test_dataset/*_tick.csv')
df2 = pd.concat([pd.read_csv(f) for f in files2])
print()
print('=== TEST DATASET ===')
print(f'Rows: {len(df2)}')
print(f'Speed mps: mean={df2.speed_mps.mean():.2f} std={df2.speed_mps.std():.4f} min={df2.speed_mps.min():.2f} max={df2.speed_mps.max():.2f}')
print(f'RSRP: {df2.serving_rsrp_dbm.min():.1f} to {df2.serving_rsrp_dbm.max():.1f}')
print(f'SINR: {df2.serving_sinr_db.min():.1f} to {df2.serving_sinr_db.max():.1f}')
print(f'HO: {df2.ho_event.sum()} ({df2.ho_event.mean()*100:.2f}%)')
print(f'RLF: {df2.rlf_event.sum()} ({df2.rlf_event.mean()*100:.2f}%)')
print(f'PP: {df2.ping_pong.sum()} ({df2.ping_pong.mean()*100:.2f}%)')
print(f'Margin dB: mean={df2.best_margin_db.mean():.2f} std={df2.best_margin_db.std():.2f}')
